### ISSUE TITLE
PR for new versions

### ISSUE THREAD

**Issue by jkarni** [snoyberg/packdeps#24]
I've been thinking of making a service that would automatically send PRs to subscribed repositories/packages with version bumps coming out of packdeps. (Checking that the subscribed packages still build would, of course, be the responsibility of CI, not of this service.) I could either do this as a separate service, or  include it in the current packdeps server - thought I'd ask to see which you'd prefer. 

(By the way, packdeps.haskellers.com seems to be down.)

**Comment by snoyberg** [comment]
Thanks for the heads-up, I bumped the hosting to a larger machine.

I'm not really in a position to maintain new code like that, but if you'd like to step in as a comaintainer of packdeps and add such functionality, I'd have no problem with it.

**Comment by jkarni** [comment]
Great - I'll either send a PR or make it a separate service.
