### ISSUE TITLE
Allow providing exceptions

### ISSUE THREAD

**Issue by ivan-m** [snoyberg/packdeps#25]
Would it be possible to have the cli version of packdeps check all dependencies except for a specified list?  I ran into this recently where one package (specifically `fgl-arbitrary`) depended upon an as-yet-unreleased version of another package (`fgl`), thus causing the travis-ci build to fail.

**Comment by snoyberg** [comment]
I see no problem with such a feature. PR welcome z

**Comment by phadej** [comment]
Resolved ^
