### ISSUE TITLE
Doesn't show reverse dependencies from custom-seup stanzas

### ISSUE THREAD

**Issue by RyanGlScott** [snoyberg/packdeps#39]
I was curious to know how many packages were depending on the `cabal-doctest` package, but http://packdeps.haskellers.com/reverse/cabal-doctest claims that there's only one! This is obviously false, though, since a wide variety of packages depend on `cabal-doctest`, but only in their `custom-setup` stanzas ([here's](https://github.com/ekmett/distributive/blob/2523b87aa022e9395e43c62720590777f0a7e04c/distributive.cabal#L42) and example). However, it appears that `packdeps-yesod` doesn't factor in `custom-setup` stanzas:

https://github.com/snoyberg/packdeps/blob/27d95d2c39ad5b3a303d52bd9e1a6bbddc01cb4d/packdeps-yesod/src/Distribution/PackDeps.hs#L190-L195

when determining reverse dependency information.

**Comment by snoyberg** [comment]
Good catch, it's worth adding. I probably won't have a chance this week or next, so PR will definitely expedite this one.

**Comment by RyanGlScott** [comment]
Well, I opened up this issue in the first place because the code is far too confusing for my feeble brain :)

1. That function appears to make some sort of distinction between "`Runtime`" things and "`TestBench`" things, for reasons that I don't understand. I have no idea where `custom-setup` stanzas fall in this dichotomy.
2. Moreover, the code that actually process the stanzas (and applies the `base` hack, etc.) expects a `CondTree`. [`setupDepends`](https://hackage.haskell.org/package/Cabal-2.2.0.1/docs/Distribution-PackageDescription.html#v:setupDepends), on the other hand, only has `[Dependency]`. It appears that one would need to significantly refactor this code to account for this, but I don't feel qualified to do so.

**Comment by snoyberg** [comment]
This is addressed in 7f341af2b2be1647a30f2a1a76ebbe6dba6e2f37

**Comment by RyanGlScott** [comment]
Awesome, thanks! I'm eagerly looking forward to this landing on http://packdeps.haskellers.com/reverse :)

**Comment by RyanGlScott** [comment]
It looks great, thanks!
