### ISSUE TITLE
"dhall-to-cabal" doesn't show up

### ISSUE THREAD

**Issue by ocharles** [snoyberg/packdeps#42]
If I search for `dhall-to-cabal`, I get no results: http://packdeps.haskellers.com/feed?needle=dhall-to-cabal.

The database was last updated recently enough that it should exist. Any idea what's up?

**Comment by snoyberg** [comment]
Good catch. Here's the issue:

* packdeps is using the `00-index.tar.gz` file from Hackage (for hysterical raisins)
* There was a bug in `cabal-install` resulting in `cabal-version: 2.0` files being excluded from `00-index.tar.gz`
* And `dhall-to-cabal` uses that versions

I'll try moving over to the 01-index.tar.gz file, if we're lucky it should be a trivial change

**Comment by snoyberg** [comment]
OK, this should be fixed now.

**Comment by ocharles** [comment]
Super, thank you!
