### ISSUE TITLE
Incorrect hlint outdated dependency

### ISSUE THREAD

**Issue by ndmitchell** [snoyberg/packdeps#49]
If I visit http://packdeps.haskellers.com/feed?needle=hlint I get told hlint has a restrictive bound on ghc 8.6.5. That's weird since hlint can depend on 8.8.*, but not 8.6 at all. I can't see how packdeps came to that conclusion.

**Comment by phadej** [comment]
There is no `ghc-8.8.1` package on Hackage, which confuses `packdeps`, `hlint` cannot use the "latest" `ghc` version on Hackage which is 8.6.5.

This is a bug or a feature depending on your POV. You usually don't want have bounds which require something which is not on Hackage, and will be resolved eventually when https://github.com/haskell-infra/hackage-trustees/issues/240 is resolved.

It's clearly a bug that packdeps says restrictive **upper bounds**, but it would need a bit of coding to show whether it's a lower or upper (or actually something in between `< x.y.z && > x.y.z`). Maybe some clever rewording, like dropping *upper*.

**Comment by ndmitchell** [comment]
Thanks, that makes sense. Sad, but never mind.
