### ISSUE TITLE
Missing package

### ISSUE THREAD

**Issue by georgefst** [snoyberg/packdeps#51]
[streamly-fsnotify](http://hackage.haskell.org/package/streamly-fsnotify) ought to be listed in [the reverse dependencies of streamly](https://packdeps.haskellers.com/reverse/streamly), among other places. [It's own list](https://packdeps.haskellers.com/reverse/streamly-fsnotify) is present.

The potential reasons for `packdeps` to have gotten confused include the package recently being deprecated, changing ownership, then being un-deprecated.

**Comment by georgefst** [comment]
Update - that third link is now broken as well. It definitely wasn't at the time of posting.

**Comment by simonmichael** [comment]
Similarly: hledger-ui should appear at https://packdeps.haskellers.com/reverse/brick .

**Comment by georgefst** [comment]
Actually, none of [my packages](https://hackage.haskell.org/user/GeorgeThomas) seem to appear on the site...

Are there particular criteria that need to met?

**Comment by snoyberg** [comment]
I'm guessing it's because you're using a very new version of cabal-the-format. Packdeps Web hasn't been updated to support the newest Cabal library.

**Comment by georgefst** [comment]
Ah, fair enough, thanks.

Come to think of it, that's probably also the reason the same packages aren't indexed by Hoogle...

**Comment by snoyberg** [comment]
Looks like this is fixed with the newest version: https://packdeps.haskellers.com/reverse/streamly-fsnotify

**Comment by georgefst** [comment]
Looks good, thanks!

@simonmichael's issue seemingly has a different cause, however

**Comment by snoyberg** [comment]
I'm guessing that may be due to the conditional dependency in the cabal file.

**Comment by simonmichael** [comment]
True! I simplified that, so the next hledger-ui release should show up in brick's reverse deps.
