### ISSUE TITLE
Why does Atom entry redirects to Hackage?

### ISSUE THREAD

**Issue by Minoru** [snoyberg/packdeps#55]
Entries in Atom feeds have links like https://packdeps.haskellers.com/feed/exact:hakyll/hakyll/4.14.0.0/2021-07-19%2005:37:30%20UTC When I open that link in browser, I am immediately redirected to the Hackage page for the package. This is inconvenient: the reason I'm subscribed to the feed is that I want to know which of my deps are outdated, and now I have to manually go to packdeps.haskellers.com to figure that out. It'd be much more convenient to me if the Atom entry linked me to https://packdeps.haskellers.com/feed?needle=exact%3Ahakyll

It appears that the redirect was there from day 1 (`Handler.Home.getFeed3R`), so this is probably intentional. I'd like to know the reason and see if it can be reconsidered.

Thank you for a nice and useful service!

**Comment by snoyberg** [comment]
Not sure there was a specific reason. If you think the other approach would be better, I'm open to a PR to implement it.

> Thank you for a nice and useful service!

❤️
